### ISSUE TITLE
portus-background container crash frequently

### ISSUE THREAD

**Issue by YunSangJun** [SUSE/caasp-services#37]
## Problem
portus-background container crash frequently.

## Status

```
kubectl get pods -n portus
NAME                                      READY     STATUS             RESTARTS   AGE
portus-mariadb-5d657759fd-68m54           1/1       Running            0          7h
portus-portus-84dfd755b4-xsxg6            1/2       CrashLoopBackOff   144        7h
portus-portus-nginx-b6597d464-nnc4x       1/1       Running            0          7h
portus-portus-registry-65bc8bb5cb-nb4lz   1/1       Running            0          7h
```

## Error log 

```
kubectl logs -f portus-portus-84dfd755b4-xsxg6 -n portus
Error from server (BadRequest): a container name must be specified for pod portus-portus-84dfd755b4-xsxg6, choose one of: [portus portus-background]
sangjunyun:portus sangjunyun$ kubectl logs -f portus-portus-84dfd755b4-xsxg6 -n portus -c portus-background
Failed to create bus connection: No such file or directory
You have not changed the FQDN configuration. Are you sure about this?
[Mailer config] Host:     portus.test.lan
[Mailer config] Protocol: https://
Failed to create bus connection: No such file or directory
[Initialization] Running: 'Registry events', 'Registry synchronization'
/usr/lib64/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): http://portus-registry.ghama.io:%!s(<nil>)/v2/token?account=portus&scope=registry%3Acatalog%3A%2A&service=portus-portus-registry%3A5000 (URI::InvalidURIError)
	from /usr/lib64/ruby/2.5.0/uri/rfc3986_parser.rb:73:in `parse'
	from /usr/lib64/ruby/2.5.0/uri/common.rb:237:in `parse'
	from /usr/lib64/ruby/2.5.0/uri/common.rb:743:in `URI'
	from /srv/Portus/lib/portus/http_helpers.rb:110:in `request_auth_token'
	from /srv/Portus/lib/portus/http_helpers.rb:48:in `perform_request'
	from /srv/Portus/lib/portus/registry_client.rb:131:in `get_page'
	from /srv/Portus/lib/portus/registry_client.rb:118:in `paged_response'
	from /srv/Portus/lib/portus/registry_client.rb:83:in `catalog'
	from /srv/Portus/lib/portus/background/sync.rb:55:in `block in execute!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:51:in `block in find_each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:124:in `find_in_batches'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/batches.rb:50:in `find_each'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:9:in `find_each'
	from /srv/Portus/lib/portus/background/sync.rb:54:in `execute!'
	from /srv/Portus/bin/background.rb:56:in `block (2 levels) in <top (required)>'
	from /srv/Portus/bin/background.rb:54:in `each'
	from /srv/Portus/bin/background.rb:54:in `each_with_index'
	from /srv/Portus/bin/background.rb:54:in `block in <top (required)>'
	from /srv/Portus/bin/background.rb:53:in `loop'
	from /srv/Portus/bin/background.rb:53:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `load'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/runner.rb:60:in `<top (required)>'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:123:in `require_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:90:in `runner'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /srv/Portus/vendor/bundle/ruby/2.5.0/gems/railties-4.2.10/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:12:in `require'
	from bin/rails:12:in `<main>'
```

**Comment by draeron** [comment]
i'm having the same issue.

```
 [Initialization] Running: 'Registry events', 'Registry synchronization'
/usr/lib64/ruby/2.5.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): http://portus-portus-nginx:%!s(&lt;nil&gt;)/v2/token?account=portus&amp;scope=registry%3Acatalog%3A%2A&amp;service=portus-portus-registry%3A5000 (URI::InvalidURIError) 
```

Versions : 
- Kubernetes: 1.9.6
- Helm: 2.8.0
- chart: 0.1.0

**Comment by draeron** [comment]
After some investigation, the problem seems to be `REGISTRY_AUTH_SILLY_REALM` configmap for the regsitry. I've changed it directly in k8s but i'm looking to fix it in the chart.

**registry-configmap.yaml:**
```yaml
  REGISTRY_AUTH_SILLY_REALM: {{ printf "http://%s:%s/v2/token" (.Values.nginx.host | default (printf "%s" (include "nginx.fullname" .))) (.Values.nginx.service.nodePort | default .Values.nginx.port) | quote }}
```

**Comment by mssola** [comment]
Closing since this has already been moved into kubic-project/caasp-services#38. Thanks!
